#!/usr/bin/with-contenv bash

[[ -f /data/settings.yml ]] && ( \
    cp /data/settings.yml /usr/local/searx/searx/settings.yml \
) || ( \
    sed -i -e "s|base_url : False|base_url : ${BASE_URL}|g" \
        -e "s/image_proxy : False/image_proxy : ${IMAGE_PROXY}/g" \
        -e "s/ultrasecretkey/$(openssl rand -hex 16)/g" \
        /usr/local/searx/searx/settings.yml \
);

exec s6-setuidgid $PUID:$PGID python /usr/local/searx/searx/webapp.py
